// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies ApS";
    extern const char* const UnityCopyright = "(c) 2022 Unity Technologies ApS. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2021.3.12f1";
    extern const char* const UnityVersionDigits = "2021.3.12";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2021;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 12;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2021.3.12f1_8af3c3e441b1";
    extern const char* const UnityVersionUnderHash_Verbose = "2021.3.12f1_8af3c3e441b1";
    extern const char* const UnityVersionUnderHash_WithParens = "2021.3.12f1 (8af3c3e441b1)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 9106371;

    extern const UInt64 UnityVersionDate = 1666106315;
    extern const char* const UnityVersionBranch = "2021.3/release";
    extern const char* const UnityVersionDisplay = "2021.3.12f1";
    extern const char* const UnityVersionDisplay_Verbose = "2021.3.12f1.git.9106371";
    extern const char* const UnityVersionRevision = "8af3c3e441b1";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2021.3.12f1 (8af3c3e441b1)";
    extern const wchar_t* const L_UnityVersion = L"2021.3.12f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies ApS"
    #define UNITY_COPYRIGHT "(c) 2022 Unity Technologies ApS. All rights reserved."
    #define UNITY_VERSION_VER 2021
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 12
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2021.3.12f1_8af3c3e441b1"
    #define UNITY_VERSION_PARENS_HASH "2021.3.12f1 (8af3c3e441b1)"
    #define UNITY_VERSION_BLD 9106371
    #define UNITY_VERSION_WIN "2021.3.12.9106371"

#endif // !RC_INVOKED
